# Generated by Django 4.0.1 on 2022-01-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfgpage', '0002_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
