# Generated by Django 4.0.1 on 2022-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfgpage', '0003_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
