# Generated by Django 4.0.1 on 2022-01-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfgadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connector',
            old_name='Type',
            new_name='type',
        ),
    ]
